spring.application.name=app-authorisation-server
spring.datasource.url=jdbc:sqlserver://localhost:1433;DatabaseName=SURY_FLUX;encrypt=false;trustServerCertificate=false
spring.datasource.username=sa
spring.datasource.password=evolvus*123
spring.datasource.driver=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.database-platform=org.hibernate.dialect.SQLServer2012Dialect
spring.jpa.hibernate.ddl-auto=update


spring.security.user.name=admin
spring.security.user.password=admin

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework=INFO

logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE



